force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Mar14TestDataFactory.cls
public with sharing class Mar14TestDataFactory {
    @TestVisible
    static List<Employee__c> empToInsert(Integer emps, String dep) {
        List<Employee__c> eList = new List<Employee__c>();
        for(Integer i=1;i<=emps;i++){
            Employee__c e = new Employee__c();
            e.name = 'Test Employee'+i;
            e.Employee_Email__c = 'test'+i+'@gmail.com';
            e.Start_date__c = Date.today().addDays(-7);
            e.Department__c = dep;
            eList.add(e);
        }
        return eList;
    }
}