force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Onboarding_Checklist__c/Onboarding_Checklist__c.object-meta.xml
<CustomObject>
    <label>Onboarding Checklist</label>
    <nameField>
        <label>Checklist Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Checklist__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Onboarding Checklists</relationshipLabel>
    <relationshipName>Onboarding_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Mar14EmployeeTriggerTest.cls
@isTest
public with sharing class Mar14EmployeeTriggerTest {
    @isTest 
    static void ifIisOne() {
        List<Employee__c> eListSales = Mar14TestDataFactory.empToInsert(25,'Sales');
        List<Employee__c> eListService = Mar14TestDataFactory.empToInsert(25,'Service');
        Test.startTest();
        try{
            Database.insert(eListSales,false);
            Database.insert(eListService,false);
        }
        catch(Exception e){

            System.assert(e.getMessage()==null);
        }
        
        Test.stopTest();
        List<Onboarding_Checklist__c> testOCsales = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListSales[0].Id];
        System.assertEquals(3, testOCsales.size());
        System.assertEquals(eListSales[0].Department__c + ' Goal', testOCsales[0].Name);

        List<Onboarding_Checklist__c> testOCservice = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListService[0].Id];
        System.assertEquals(3, testOCservice.size());
        System.assertEquals(eListService[0].Department__c + ' Goal', testOCservice[0].Name);
    }
    @isTest
    static void ifIisTwo() {
        List<Employee__c> eListSales = Mar14TestDataFactory.empToInsert(25,'Sales');
        List<Employee__c> eListService = Mar14TestDataFactory.empToInsert(25,'Service');
        Test.startTest();
        try{
            Database.insert(eListSales,false);
            Database.insert(eListService,false);
        }
        catch(Exception e){

            System.assert(e.getMessage()==null);
        }
        Test.stopTest();
        List<Onboarding_Checklist__c> testOCsales = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListSales[0].Id];
        System.assertEquals(3, testOCsales.size());
        System.assertEquals(eListSales[0].Department__c + ' Job Training', testOCsales[1].Name);

        List<Onboarding_Checklist__c> testOCservice = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListService[0].Id];
        System.assertEquals(3, testOCservice.size());
        System.assertEquals(eListService[0].Department__c + ' Job Training', testOCservice[1].Name);
    }
    @isTest
    static void ifIisThree(){
        List<Employee__c> eListSales = Mar14TestDataFactory.empToInsert(25,'Sales');
        List<Employee__c> eListService = Mar14TestDataFactory.empToInsert(25,'Service');
        Test.startTest();
        try{
            Database.insert(eListSales,false);
            Database.insert(eListService,false);
        }
        catch(Exception e){

            System.assert(e.getMessage()==null);
        }
        Test.stopTest();
        List<Onboarding_Checklist__c> testOCsales = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListSales[0].Id];
        System.assertEquals(3, testOCsales.size());
        System.assertEquals(eListSales[0].Department__c + ' Role', testOCsales[2].Name);

        List<Onboarding_Checklist__c> testOCservice = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListService[0].Id];
        System.assertEquals(3, testOCservice.size());
        System.assertEquals(eListService[0].Department__c + ' Role', testOCservice[2].Name);
    }
    @isTest
    static void isFailure(){
        List<Employee__c> eListSales = Mar14TestDataFactory.empToInsert(25,'Marketing');
        List<Employee__c> eListService = Mar14TestDataFactory.empToInsert(25,'Social Media');//Because Department__c is picklist with 2 values(Sales or Service)
        Test.startTest();
        try{
            Database.insert(eListSales,false);
            Database.insert(eListService,false);
        }
        catch(Exception e){

            System.assert(e.getMessage()!=null);
        }
        Test.stopTest();
        List<Onboarding_Checklist__c> testOCsales = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListSales[0].Id];
        System.assert(testOCsales.size()==0);

        List<Onboarding_Checklist__c> testOCservice = [SELECT Id, Name FROM Onboarding_Checklist__c WHERE Employee__c=: eListService[0].Id];
        System.assert(testOCservice.size()==0);
    }
}