force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <label>Custom Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Order__c/fields/IsOrderValid__c.field-meta.xml
<CustomField>
    <fullName>IsOrderValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsOrderValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Validation_Errors__c.field-meta.xml
<CustomField>
    <fullName>Validation_Errors__c</fullName>
    <label>Validation Errors</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsOrderValid__c.field-meta.xml
<CustomField>
    <fullName>IsOrderValid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsOrderValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Validation_Errors__c.field-meta.xml
<CustomField>
    <fullName>Validation_Errors__c</fullName>
    <label>Validation Errors</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/feb26Afternoon.cls
public with sharing class feb26Afternoon {
    @future
    public static void futureMethod(Id orderId){
        List<Custom_Order__c> orderList = ([Select Validation_Errors__c, Name, IsOrderValid__c, Owner.Email from Custom_Order__c where Id = : orderId]);
        For(Integer i=0;i<orderList.size();i++){
            if(orderList[i].IsOrderValid__c){
                orderList[i].Validation_Errors__c = 'Dear ' + orderList[i].Owner.Name +'\n';
                orderList[i].Validation_Errors__c += 'Your order is Valid';
            }
            else if(orderList[i].IsOrderValid__c == false){
                orderList[i].Validation_Errors__c = 'Dear ' + orderList[i].Owner.Name +'\n';
                orderList[i].Validation_Errors__c += ' Order Invalid : \n'+ orderList[0].Validation_Errors__c;
            }
            EmailManager.sendMail(orderList[i].Owner.Email,'Validation Status',orderList[i].Validation_Errors__c);
        }
    }
}